Fix/477/apidoc pipeline
sakuli/sakuli pull request #478
Opened 2020-09-02 08:02 UTC by s1hofmann

2020-09-03 08:20 UTC, svettwer requested changes

2020-09-03 08:20 UTC, svettwer commented on .travis.yml
> +            tags: true
Are you sure that all dev dependencies are still available at this point?
Due to `skip_cleanup: false` in the previous steps and the step itself, all changes to the repo should be `git stash --all` including the `node_modules` folder containing the typedoc dependency. As `lerna` is installed globally, this is not an issue.

Maybe we should change `skip_cleanup` to `true`.

2020-09-17 07:11 UTC, svettwer commented on .travis.yml
> +            tags: true
The [docs on travis](https://docs.travis-ci.com/user/deployment/pages/) state:
> Make sure you have `skip_cleanup` set to `true`

2020-09-17 11:03 UTC, cliffle commented on .travis.yml
> +        - lerna run typedoc
When we create the typedocs before the deploy stage, we should add the `docs` folder to `.npmignore` to prevent it from publishing to npm.

2020-09-17 11:13 UTC, cliffle commented on .travis.yml
> +        - lerna run typedoc
Never mind.. the docs aren't created in the packages... The `.npmignore` in the root level confused me

2020-09-17 11:13 UTC, cliffle approved these changes

2020-09-21 04:56 UTC, svettwer approved these changes

2020-09-21 04:56 UTC, merged